the-programmers-hangout/website

.gitattributes
codegen.yml
package-lock.json
package.json
src/generated/graphql.ts

Added scripts for generating typescript definitions of graphql queries

typescript type generations from graphql

---

src/components/DocsLayout/index.tsx
src/components/DocsLayout/styles.tsx
src/components/DocsSidebar/index.tsx
src/components/DocsSidebar/style.tsx
src/components/DocsSidebar/styles.tsx
src/components/Layout/layout.scss

ui: style docs

---

src/components/Sidebar/index.tsx
src/components/Sidebar/styles.tsx
src/pages/docs.tsx

feat: link to docs from sidebar

---

src/content/docs/php/design-patterns/singleton.md

Re from: https://github.com/the-programmers-hangout/website/pull/6

Added singleton article

---

.prettierrc

This adds the remaining options of Prettier to avoid local config to be different from contributor to contributor.

chore: add all prettier options

---

src/components/DocsSidebar/useBuildTree.tsx

ramda is a big boy module, now it is a small boy module

added tree-shaking to ramda import

---

gatsby-config.js
package-lock.json
package.json
src/components/DocsLayout/index.tsx
src/components/Layout/index.tsx
src/components/Markdown/index.tsx
src/components/Markdown/styles.tsx
src/design/typography.ts
src/globalStyles.tsx
src/templates/languagePost.tsx

This imports and prefetches Oxygen and Montserrat, sets Oxygen as the body font, with a base of 18px.
More importantly, this sets up a vertical rythm system for the markdown content.
Rules being:
- Base/body font at 18px, 26px line-height
- H6 through H1 being powers of 1.1487 (following modular scaling)
- Line-height is always a multiple of the base line-height (25px)
See: https://zellwk.com/blog/why-vertical-rhythms/
closes #14

feat: set up typography

---

gatsby-node.js
scripts/buildHelpers.js

This will help for when we want to add a button for editing the current file

Generating a github link for each of the markdown files

---

src/components/ResourceHeader/index.tsx
src/components/ResourceHeader/styles.tsx
src/components/StackedAvatars/index.tsx
src/components/StackedAvatars/styles.tsx

feat: stacked avatars for contributors

---

src/components/ResourcesSidebar/index.tsx

feat: redirect to home page on clicking the resources banner

---

src/components/ResourcesSidebar/index.tsx
src/components/ResourcesSidebar/styles.tsx

This adds the menu to the resources sidebar.

feat: add menu to resources sidebar

---

src/globalStyles.tsx

This was removed by mistake from 2195e0c138a3abd974b5198702f65c7583e1dcea, oops.

feat: reimplement text smoothing

---

src/components/Container/styles.tsx
src/components/Footer/styles.tsx
src/components/Header/index.tsx
src/components/Header/styles.tsx
src/components/Layout/index.tsx
src/components/Layout/styles.tsx

I'm refactoring the container styles in order to improve container code simplicity, thereby reducing future problems with container adjustments.
This does not yet address CSS jitter.

Refactor container Styles

---

gatsby-browser.js
gatsby-config.js
package-lock.json
package.json
src/components/Markdown/index.tsx

I spent probably 4-5 hours trying to figure out how to do this on the server side which would be much more optimal but currently this is being done on the client side.
If we go with this approach we're going to have to manually add new language support as more languages are added to the resources.

Added syntax highlighting

---

src/components/Header/index.tsx

I'd like to add a link for the topmost image to redirect to the index page. We probably should invest some thought into the index page as well.

Add index link to header logo

---

src/content/resources/javascript/iterative-vs-functional.md

I fixed the example on ``Array#every`` and also a little typo: ``inludes`` -> ``includes``.

fixed Array#every example

---

src/content/docs/php/pdo/prepared-statements.md

This is a frequently asked question so I figured I'd throw together a tiny article on the topic

resources: Added article for prepared statements with PHP

---

src/content/site/about.md

fix: added fox to server owners

---

src/content/resources/javascript/spread-operator.md

Hello! I added a post on the spread operator in Javascript.

feat: spread operator post

---

package.json

Sorted using `npx sort-package-json`.

style: sort package.json

---

src/content/resources/javascript/spread-operator.md

fix: typo in spread operator post

---

src/components/ResourceBreadcrumb/index.tsx
src/components/ResourceBreadcrumb/styles.tsx
src/components/ResourceHeader/index.tsx
src/components/ResourceHeader/styles.tsx
src/components/ResourcesSidebar/useBuildTree.tsx
src/templates/languagePost.tsx
src/utils/index.ts

closes #31
Note: currently, intermediate pages don't exist, we have to create them.

feat(resources): implement breadcrumbs

---

gatsby-config.js
package-lock.json
package.json

feat: add article anchors

---

src/content/resources/kotlin/native/creating-c-bindings.md

I wrote a tiny article on interoperability between Kotlin/Native and C.

Create Kotlin interop article

---

src/components/Markdown/styles.tsx
src/components/MobileHeader/index.tsx
src/components/MobileHeader/styles.tsx
src/components/ResourceBreadcrumb/styles.tsx
src/components/ResourceHeader/index.tsx
src/components/ResourceHeader/styles.tsx
src/components/ResourcesLayout/index.tsx
src/components/ResourcesLayout/styles.tsx
src/components/ResourcesSidebar/index.tsx
src/components/ResourcesSidebar/styles.tsx

First iteration of responsive resources, including a burger nav.

feat: responsive resources

---

src/components/ResourcesLayout/styles.tsx
src/components/ResourcesSidebar/index.tsx
src/components/ResourcesSidebar/styles.tsx

closes #70
This adds a scrollbar to the resources sidebar

feat(resources): add scrollbar to sidebar

---

src/components/ResourcesSidebar/styles.tsx

This adds hover/active states to the sidebar

feat(resources): improve UX of sidebar

---

gatsby-browser.js
src/SidebarProvider.tsx
src/components/Container/styles.tsx
src/components/Footer/index.tsx
src/components/ResourceBreadcrumb/index.tsx
src/components/ResourceHeader/styles.tsx
src/components/ResourcesLayout/index.tsx
src/components/ResourcesSidebar/styles.tsx
src/components/ResourcesSidebar/useBuildTree.tsx
src/pages/about.tsx
src/pages/rules.tsx

Removes some dead code, clean up types and auto-format files.

refact: general cleanup

---

src/components/ResourceBreadcrumb/index.tsx
src/components/ResourcesList/index.tsx
src/components/ResourcesSidebar/index.tsx
src/utils/index.ts

feat: standarize titles

---

src/components/ResourcesSidebar/index.tsx
src/hooks/useLockBodyScroll.tsx
src/layouts/ResourcesLayout/index.tsx

This prevents the annoying/buggy scrolling that happens when scrolling on mobile

fix(resources): lock body on opening mobile sidebar.

---

src/content/resources/cpp/pragma-once-faq.md

Converting a pin in #cpp to a resource. With memes

resource: Add pragma-once-faq for C++

---

src/components/DiscordButton/index.tsx
src/components/DiscordButton/styles.tsx

Also made it into an `a` tag for accessibility improvements.

Add link to Discord button

---

src/components/Waves/styles.tsx

This isn't my favourite fix, but for legibility, this is necessary. A better fix would be to tweak the original SVG colors so they are less vibrant.
Closes #99

ui(home): darken waves, improve legiblity on menu

---

src/components/Markdown/index.tsx

This PR adds syntax highlighting support for the languages already used in the resources. It also covers the languages which are requesting resources (Java, C++/C)

feature(resources): Add syntax highlighting for languages used in articles

---

src/components/ResourceHeader/index.tsx
src/components/ResourceHeader/styles.tsx

feat(resources): add popover to contributors

---

src/content/resources/javascript/variables.md

Add a new article for Variables in Javascript.
Added some basic information and usage about JS Variables, discussed dynamic typing & discussed let and const.

content(js): add variable article

---

src/components/Header/styles.tsx
src/components/Waves/styles.tsx

fixes #128
Also needed to add pointer-events to the waves preventing any interaction on content.

ui: fix header waves being cut

---

src/components/Header/styles.tsx
src/components/Waves/styles.tsx
src/layouts/Layout/styles.tsx

ui: update homepage color to match resources

---

src/components/ResourcesList/index.tsx
src/components/ResourcesSidebar/index.tsx

Enforce Order of languages in Resources List

---

src/content/resources/javascript/es6/arrow-functions.md

I've created a basic guide on ES6 arrow functions. I'm not so sure how great the quality is, but I've managed to cover the following:
- Arrow Function Syntax
- Handling of the keyword this in arrow functions
I believe that I covered the important content. I would greatly appreciate any input.

Added Basics about Arrow Functions

---

src/templates/languagePost.tsx

feat(resources): improve SEO by attaching excerpt as description

---

src/content/resources/javascript/iterative-vs-functional.md

Some small typos in the code examples for the iterative vs functional JS
page have been fixed up.

fix(resources): fix typos in js resources

---

README.md

Current banner link seems to be 404.
Cheers

Update broken banner link in README

---

src/content/resources/python/operators.md

This article doesn't include all the operators in Python, but covers the most common operators - arithmetic, comparison and assignment operators as well as operator precedence, explaining the order they are executed in. This article is more geared towards beginners due to only covering common, mostly simple operators, but if you guys think it is a useful article, could be expanded in future to cover other operators such as bitwise operators. However that article may reach several hundred lines and may need to be split up into different articles. Make any edits to improve the explanations or examples you want.

Added Article about Operators In Python

---

src/components/HomeMobileHeader/index.tsx
src/layouts/ArchivesLayout/index.tsx
src/layouts/ColumnLayout/index.tsx
src/layouts/ResourcesLayout/index.tsx

feat: support custom mobile header title

---

gatsby-config.js
package-lock.json
package.json
src/content/archives/what-is-docker.md
src/content/archives/what-is-elixir.md
src/content/archives/what-is-graphql.md
src/content/archives/what-is-haskell.md
src/content/archives/what-is-kotlin.md
src/content/archives/what-is-lisp.md

pre-required by #170, it will be a lot easier to manage them locally

feat(archives): transfer locally, instead of fetching from git

---

src/components/HomeHeader/styles.tsx

fix: make site title much smaller mobile/tablet

---

src/content/archives/what-is-docker.md
src/content/archives/what-is-graphql.md
src/content/archives/what-is-lisp.md

content(archives): format codeblocks

---

src/content/resources/cpp/multidimensional-arrays.md

I saw a conversation about multidimensional arrays in the c++ channel so I wrote an article about multidimensional arrays in c++ for your website. Please let me know if there are any problems with it or if there's anything that you want me to change.

Created a article name multidimensional-arrays for c++

---

src/content/resources/java/class.md

This article was too complex for a beginner. I have taken out discussion of super() as well as reduced the discussion of constructors in general. Other articles will be created to explore those topics in more depth.

Simplify Java/Class article

---

src/content/site/about.md
src/content/site/rules.md

Corrected the following issues:
- Fixed possession of some nouns.
- Changed improper uses of 'which' → 'that'
- Cleaned up/clarified some prose
- & Corrected common grammatical errors
😄

Correct Grammatical Errors

---

gatsby-node.js
src/components/ResourcesList/index.tsx
src/content/resources/cpp/intro.md
src/content/resources/java/intro.md
src/content/resources/javascript/intro.md
src/content/resources/kotlin/intro.md
src/content/resources/php/intro.md
src/content/resources/python/intro.md
src/templates/languageHome.tsx
src/types/index.d.ts

closes #142
This adds an intermediate page for each languages. To be iterated on.

feat(resources): create intro page for each language

---

src/components/HomeHeader/styles.tsx

This removes the awkward animation moving from home to the rules page

ui: improve bad animation on waves

---

src/content/resources/java/streams.md

I added an article about Streams in Java. I would appreciate feedback about my article, since this is the first time i wrote one. It would also be nice if someone could look over it to find mistakes, because english is not my native language.
If we would get an article about Lambdas in Java, this should definetly be a recommended article, before reading mine.

Add Stream resource for Java

---

src/components/HomeHeader/index.tsx
src/components/HomeHeader/styles.tsx
src/components/Sidebar/index.tsx
src/components/Sidebar/styles.tsx

Adds a link to the forum. This needs to wait until the certificate to https://forum.theprogrammershangout.com/ is fixed.

feat: tweak menu links & add link to forum

---

src/SidebarProvider.tsx
src/components/ArchivesSidebar/index.tsx
src/components/ResourcesSidebar/index.tsx
src/layouts/ColumnLayout/index.tsx

closes #183
This closes the sidebar when clicking on a link, on mobile.

feat: improve sidebar

---

src/components/DiscordButton/styles.tsx
src/components/HomeHeader/styles.tsx
src/components/Waves/styles.tsx
src/images/waves-bot.svg
src/images/waves-top.svg

#187 
Before: [https://gyazo.com/0d0c682950553efe75d27cee365d6ab8](https://gyazo.com/0d0c682950553efe75d27cee365d6ab8)
After: [https://gyazo.com/4181d3d9a6f8d4d678cf46d06192a2aa](https://gyazo.com/4181d3d9a6f8d4d678cf46d06192a2aa)
Shouldn't change how it appears on other browsers.

IE11 Homepage Support

---

src/components/Sidebar/index.tsx
src/components/Sidebar/styles.tsx
src/layouts/Layout/index.tsx
src/layouts/index.tsx

Changed the "Rules" and "About" page layout to "Archive" and "Resource" page design

Rules and about page layout change

---

src/components/Home/index.tsx
src/components/Home/styles.tsx
src/layouts/HomeLayout/index.tsx

Cleaned up Home Header as it serves only Home page

Home header cleanup

---

src/content/archives/what-is-julia.md
src/content/archives/what-is-redis.md
src/content/archives/what-is-rust.md
src/content/resources/javascript/promises/async-await.md
src/content/resources/javascript/variables.md

Add new Tech Spotlight archives (archived in Gitlab but not on the website):
- what-is-julia
- what-is-redis
- what-is-rust
Also updated my discord ID in previous content to fix the user avatar for those articles.

content(archive): add new archived spotlights to website

---

src/content/archives/what-is-svelte.md

Add the content from the archived `What is Svelte` tech spotlight to the website.

(content): add svelte tech spotlight

---

scripts/fetchUsers.js

User#displayAvatarURL is a method, but is not being called, which causes the output to not include avatars.
Additionally, use the BOT_TOKEN var instead of grabbing from env again, and use User#tag getter instead of manually doing it, and remove unused Writable.

fix(fetchUsers): call displayAvatarURL

---

gatsby-config.js
package-lock.json
package.json
src/components/PageContent/index.tsx
src/components/PageContent/styles.tsx
src/components/Toc/index.tsx
src/components/Toc/styles.tsx
src/content/site/rules.md
src/pages/about.tsx
src/pages/rules.tsx
src/templates/languagePost.tsx
src/types/index.d.ts
src/utils/index.ts

This is a first implementation of the table of contents!

feat: support table of contents in resources, about, and rules

---

tsconfig.json

chore: use es2019 lib in tsconfig

---

src/components/Markdown/styles.tsx

ui(resources): style blockquotes

---

src/content/resources/javascript/promises/converting-a-callback.md

render preview: https://deploy-preview-258--tph.netlify.app/resources/javascript/promises/converting-a-callback.md/

content(resources): add resource about converting a callback to a promise

---

src/content/resources/javascript/promises/async-await.md
src/content/resources/javascript/promises/intro.md

Small tidy up + tried to stay away from `foo`/`bar` examples.

content(resources): update/tweak JS promises resources

---

src/content/site/rules.md

~~Do not merge yet, there is a bug with the table of contents that causes a white page~~
Ready to merge once content is ready.
(Typography improved, bug with table of contents fixed)

content(rules): first iteration of new rules

---

LICENSE
package.json
src/content/resources/web-development/deploying-a-site-with-netlify.md

Added a new resource on how to deploy a site with Netlify
Changed the description and keywords in package.json
Changed the LICENSE year from 2015 to 2020

Added a new resource, changed the year in LICENSE and updated package.json

---

src/content/site/rules.md

feat(resources): Add bullet points to list items in the rules

---

src/content/site/rules.md

Update the phrasing of the Academic Dishonesty rule based on feedback discussed in Discord. The old phrasing made it sound like this was ok to talk about in TPH, but it was actually talking about what academic dishonesty is. This was reworded to remove the source of confusion.
Old:
```
This is where you cheat on your school work, pay someone to do your school work or try to avoid your school work in any way. It's unethical and will not be tolerated here.
```
New:
```
This means cheating on on your school work, paying someone to do your school work or trying to avoid your school work in any way. It's unethical and will not be tolerated here.
```

content(rules): update academic dishonesty phrasing

---

src/content/site/rules.md

Fixes a small typo with "This means cheating on on ....."

content(rules): fix typo with on being included twice

---

src/content/resources/topic/projects/http-project-guide/chapter-01.md
src/content/resources/topic/projects/http-project-guide/chapter-02.md
src/content/resources/topic/projects/http-project-guide/chapter-03.md
src/content/resources/topic/projects/http-project-guide/chapter-04.md
src/content/resources/topic/projects/http-project-guide/chapter-05.md
src/content/resources/topic/projects/http-project-guide/chapter-06.md
src/content/resources/topic/projects/http-project-guide/chapter-07.md
src/content/resources/topic/projects/http-project-guide/chapter-08.md
src/content/resources/topic/projects/http-project-guide/chapter-09.md
src/content/resources/topic/projects/http-project-guide/chapter-10.md
src/content/resources/topic/projects/http-project-guide/chapter-11.md
src/content/resources/topic/projects/http-project-guide/chapter-12.md
src/content/resources/topic/projects/http-project-guide/chapter-13.md
src/content/resources/topic/projects/http-project-guide/chapter-14.md
src/content/resources/topic/projects/http-project-guide/intro.md

Big chunk of content.
All pulled in from https://github.com/jkbbwr/http-project-guide
This project will give you a a-z guide to help you build a http server

feat(resources) add http-project-guide

---

src/content/resources/topic/projects/intro.md

fix(resources): hotfix to give project/resources an item with a relative path

---

src/components/Markdown/styles.tsx

ui: improve headings typography

---

src/components/HeaderBarebone/index.tsx
src/components/HeaderBarebone/styles.tsx

ui: tweak header, make it much smaller

---

src/components/404LinkCorrection/index.tsx
src/components/404LinkCorrection/styles.tsx
src/pages/404.tsx
src/pages/archives/404.tsx
src/pages/resources/404.tsx
src/pages/styles.tsx

Improvements in 404 pages

---

src/content/resources/language/javascript/iterative-vs-functional.md

Just looked weird to have the for loop's condition displayed in that order.

Minor code example change

---

gatsby-config.js
gatsby-node.js
generated/graphql.ts
package-lock.json
package.json
src/components/Markdown/index.tsx
src/components/ResourcesHomeContent/index.tsx
src/components/ResourcesList/index.tsx
src/components/ResourcesSidebar/index.tsx
src/content/site/faq.md
src/pages/about.tsx
src/pages/faq.tsx
src/pages/rules.tsx
src/templates/archive.tsx
src/templates/resourceHome.tsx
src/templates/resourcePage.tsx
src/types/index.d.ts
src/utils/index.ts

I ported mostly every thing to support Mdx plugin.
There is unresolved issues: When I try to add plugin (`gatsby-remark-auto-headers-improved`) to Mdx plugin it throws a load of errors. It's most probably an upstream bug I need more information to open an issues on the repo.
Edit: Installing the plugin with npm and using it Mdx plugins works.

feat: Implement Mdx

---

src/components/DiscordButton/index.tsx
src/components/DiscordButton/styles.tsx
src/components/Home/styles.tsx
src/components/Markdown/styles.tsx
src/content/site/about.md

this closes #232 
Basically uses MDX now that it's possible to use
**Before**
**After**

feat(about): convert join us to a button

---

src/components/ResourcesSidebar/index.tsx

Dirty, temporary fix to hide the ugly intro page for the projects

fix: hide intro page for projects

---

src/components/HeaderBarebone/styles.tsx

Fix Header Box visibility issue for Firefox

---

src/content/archives/what-is-discordjs.md

Added discord.js spotlight after converting to a website friendly format. Please check if the format is correct and let me know if you need edits somewhere.

content(archives): add discordjs spotlight

---

gatsby-node.js
src/components/PageNavigation/index.tsx
src/components/PageNavigation/styles.tsx
src/templates/resourcePage.tsx

There are many hacky things I did in CSS for the component would love a review on it.
Problems I encountered while testing: 
You can't navigate into subdirectories from a parent directory rather only files.
If there isn't any change I will mark PR as complete.

Feature page navigation

---

src/components/PageNavigation/index.tsx
src/components/PageNavigation/styles.tsx
src/templates/resourcePage.tsx

Formats the code with prettier and clean up the styles a bit.

ui: tweak page navigation

---

src/components/Home/index.tsx
src/components/Sidebar/index.tsx
src/content/site/bots.md
src/pages/bots.tsx

This PR adds a bots page to the website detailing the user facing bots, their function, and useful commands.

Add bots page to website

---

src/content/site/faq.md

added board member/retired staff description in the faq page

added board member/retired staff description

---

src/content/site/bots.md

This PR adds:
* Source links to all bots
* List of passive/staff-only bots
* Replaces HotBot with Polly

Update bots page to include polly & passive bots

---

src/components/Role/index.tsx
src/components/Role/styles.tsx
src/content/site/faq.md

ui(faq): make roles badge-like using MDX, tweak list of roles

---

src/components/Role/styles.tsx
src/content/site/faq.md

ui(faq): tweak role colors

---

src/components/Markdown/styles.tsx
src/components/ResourcesHomeContent/styles.tsx

ui: fix links underline

---

src/components/ResourcesHomeContent/styles.tsx

fix: resource link in light mode

---

gatsby-config.js
package-lock.json
package.json

Original owner dropped support: https://github.com/escaladesports/legacy-gatsby-plugin-prefetch-google-fonts

chore: use fork of gatsby-plugin-prefer-google-fonts

---

gatsby-config.js
src/components/Home/styles.tsx
src/components/HomePartner/styles.tsx
src/components/Markdown/styles.tsx
src/design/typography.ts

ui: swap inter for ibm plex sans, and oxygen mono for ibm plex mono

---

src/content/site/rules.md

Currently being discussed among admins.

Restructure and tweak rules

---

src/content/site/bots.md
src/content/site/rules.md

This PR adds Judgebot information to the bots page
Adds `:stop_sign` emote reaction as an additional way to alert staff of rule breaking content on the rules page

feat: Update moderation information

---

src/components/Home/index.tsx
src/components/Sidebar/index.tsx
src/content/site/begginers.md
src/pages/begginers.tsx

This is a copy of the #begginers channel in the discord server and can provide beginners with the information before they join the discord server.

added begginers page

---

src/content/archives/what-is-ansible.md
src/content/archives/what-is-symfony.md

This PR adds the ansible and symfony spotlights.

Add Ansible and Symfony spotlights

---

src/content/archives/what-is-ansible.md
src/content/archives/what-is-discordjs.md
src/content/archives/what-is-docker.md
src/content/archives/what-is-elixir.md
src/content/archives/what-is-graphql.md
src/content/archives/what-is-haskell.md
src/content/archives/what-is-julia.md
src/content/archives/what-is-kotlin.md
src/content/archives/what-is-lisp.md
src/content/archives/what-is-redis.md
src/content/archives/what-is-rust.md
src/content/archives/what-is-svelte.md
src/content/archives/what-is-symfony.md

This PR makes the formatting across spotlights consistent with each other to provide a better reading and usability experience.

feat: Make spotlight formatting consistent across articles

---

src/content/archives/what-is-sqlite.md

feat: add sqlite spotlight

---

src/components/Header/index.tsx

This pull request if for issue #392

Display author name when only one contributor

---

.github/workflows/lint.yml

Implements a `lint` workflow to run on every PR against `master`

CI | Lint | Implement "lint" workflow

---

src/content/resources/topic/projects/http-project-guide/chapter-12.md
src/content/resources/topic/projects/http-project-guide/chapter-13.md

Headers for chapter 12 & 13 in the HTTP project don't match their chapter numbering in front matter.

Fix chapter 12 & 13 headers

---

src/content/site/rules.md

feat: add minimodding, webscraping, drama rules

---

package-lock.json
package.json
src/components/HeaderBarebone/index.tsx
src/components/HeaderBarebone/styles.tsx
src/components/PageContent/styles.tsx

Note: This a WIP for issue #347.
The first commit contains a proof of concept that uses debouncing idea described in [https://css-tricks.com/styling-based-on-scroll-position/](https://css-tricks.com/styling-based-on-scroll-position/) to record `window.scrollY` value and renders the `BoxedTitle` base on the value. The box is hidden when the value of `window.scrollY` is greater than 30. (component class structure is based on example on [https://fettblog.eu/typescript-react/components/#class-components](https://fettblog.eu/typescript-react/components/#class-components))
The class-style React component is used to register an event listener for scrolling event.
Next is to either render new style of `HeaderWrapper` and `BoxedTitle` when the value of `widow.scrollY` is greater than 250.

[Feature/Design] Style new resources header

---

README.md

Banner URL at top of Readme was dead

Fix Dead Link

---

src/content/resources/language/c-sharp/access-modifiers.md
src/content/resources/language/c-sharp/coding-conventions.md
src/content/resources/language/c-sharp/intro.md

I created following pages:
- intro.md
- coding-conventions
- access-modifiers.md
_Some people have already checked the content of the pages and said that it's fine._
_If you would like to review it further, please feel free to do so!_

Add c-sharp resources

---

src/templates/archive.tsx

Display the author of a tech spotlight on the page 

---

src/content/resources/topic/mobile-development/flutter-intro.md

Added Flutter resources :D
(This PR is part of my hacktoberfest contributions)
- Added links for flutter website and the official first app tutorial on the flutter website
- Added a few video/text based series about making flutter apps by Fireship.io and the Flutter team

added flutter resources

---

.yarnrc.yml

@SagnikPradhan you've put work on this a year ago but right now it's not working, and don't have the energy to investigate further, so reverting to node_modules.
If you want to do more yarn work, feel free to pick this up, but been running into this: https://github.com/yarnpkg/berry/issues/4872

chore: use node modules for yarn

---

src/content/resources/language/c-sharp/intro.md
src/content/spotlights/what-is-dot-net.md

Updated authors
