the-programmers-hangout/website

src/components/StackedAvatars/styles.tsx
There was an issue with the flex that could cause the contributor images to get squished. `flex-shrink: 0` prevents this.
=> fix: fix avatar size to keep proportions

gatsby-config.js, gatsby-node.js, package-lock.json, package.json, src/layouts/index.tsx, src/pages/404.tsx, src/pages/about.tsx, src/pages/index.tsx, src/pages/resources.tsx, src/pages/rules.tsx, src/templates/languagePost.tsx
closes #40
This was surprisingly easy. A main layout file renders whatever layout depending on the context.
To avoid clashing with #39, I'm avoiding moving the layouts to `/layout`, but that's in the pipeline, after.
=> feat: persist layout state across pages

src/components/ResourceHeader/index.tsx, src/components/ResourceHeader/styles.tsx, src/content/resources/php/design-patterns/singleton.md, src/templates/languagePost.tsx
Closes #33
Closes #34 
This adds external resources in the resource header. Should this be in the footer? Let's see how it feels.
Note, it's impossible to currently support the groups of links like it was done in the PHP Singleton file, see originally. This is to resolve, but out of scope.
```
Here's a couple links which will help you understand Singletons better.
- https://en.wikipedia.org/wiki/Singleton_pattern	
- https://phpenthusiast.com/blog/the-singleton-design-pattern-in-php	
- https://phptherightway.com/pages/Design-Patterns.html#singleton	
- https://www.php.net/manual/en/language.oop5.static.php	
- https://www.php.net/manual/en/language.oop5.late-static-bindings.php	
- https://en.wikipedia.org/wiki/Static_(keyword)
- https://en.wikipedia.org/wiki/Null_coalescing_operator	
- …
```
=> feat: support external resources

src/components/ResourceHeader/index.tsx, src/components/StackedAvatars/index.tsx
No real harm here, just very annoying to get the warning during development, and a best practice.
=> fix: add key to mapped items

src/components/ResourceBreadcrumb/index.tsx
Partly cherry-picked from #63.
Refactored into functional, and removed dashes in route name.
Next up would be:
1. converting some specific words into capital: PHP, PDO.
2. converting the name of the page (Title Cased?)
3. possible treating over name of the page, for example, words like `vs`, or articles like `the`, in Title Case should not be capitalized.
Xetera judge my Ramda usage.
Re: @Xetera and @aerori 
Do we want /Home/Resources in the breadcrumbs? My first implementation of breadcrumbs skipped them as I found them very verbose (and saw no real benefit to head back to home).
Follow up @ #68
Deploy preview: https://deploy-preview-67--tph.netlify.com/resources/javascript/iterative-vs-functional.md
=> feat: capitalize breadcrumbs

src/SidebarProvider.tsx, src/components/ResourcesSidebar/index.tsx, src/hooks/useSidebar.tsx
@veksen so here are a few things about this PR:
- Your context value is not memoized and is being used as inline JSX. This will make all subscribed components re-render on every update, leading to performance problems. The `useMemo` will help with this problem.
- Subscribers to context should use `React.memo` for optimization.
- I think the function `selectFirstLevel` is not really doing anything 🤔right? Anyhow for optimization, it should be removed.
The `ISidebarContextInterface` is incorrectly imported as `SidebarContextInterface`
=> Fixing up the sidebar context

src/ThemeProvider.tsx
90%+ of Discord users seem to prefer darkmode, so it makes sense to default to it.
=> feat: default to darkmode instead of lightmode

src/content/resources/javascript/promises/async-await.md
Add a basic article in the Promises section of Javascript on Async / Await.
There are possibly scenarios I have missed or not properly explained here, as it is my first contribution to the site. If you need me to make any changes feel free to suggest.
- Async / Await article for JS resources section.
Referenced in #87
=> feat(content): add async await js article

src/content/resources/javascript/iterative-vs-functional.md
I wrote a tiny article with examples of how Array.filter, .reduce and .map can be used (#87)
=> resources: Create efficient javascript arrays resource

src/content/resources/java/generics-in-java.md
I wrote a tiny article explaining how Generics work in Java and how we can use them. (#89)
=> content(resources): Add generics in java article

src/components/Markdown/styles.tsx
It was especially bad in dark mode:
Now:
=> ui(resources): style markdown links

src/content/resources/javascript/promises/intro.md
Fix broken links in Promise JS article.
Before, these links sent the user to a 404, and now the callbacks one works correctly and the arrow functions link was removed (as this article doesn't exist).
=> resource: fix broken links in js promise article

src/components/Header/styles.tsx
=> ui: a11y fix for header active color

src/components/Markdown/styles.tsx
updated css for image and anchor tags
closes #143
=> #143 Resources: very long links and wide images break mobile

src/content/resources/javascript/es6/arrow-functions.md
Fixed discord tag on the arrow functions article, as discord tags are case-sensitive. The tag should now be accurate. This should fix the profile picture not appearing on the article.
=> Fixed Discord Tag

src/LocationProvider.tsx, src/components/ResourcesSidebar/index.tsx, src/components/ResourcesSidebar/useMatchingPath.tsx, src/hooks/useLocation.tsx, src/layouts/Layout/index.tsx, src/layouts/index.tsx
This greatly improves the UX by fixing the issue of the sidebar being improperly collapsed on hitting a particular URL.
By the same time, refactor the `location` to a provider, to avoid passing it around as prop.
=> feat(resources): improve sidebar ux

src/content/site/rules.md
Currently, some of the links from the Table of Contents do not correctly link to the anchors in the page. It seems that the reason for this is that the links in the ToC are camel case, wheras the anchors in the Gatsby generated page are all lowercase. 
IE: 
`https://theprogrammershangout.com/rules#What-is-ModMail` vs `https://theprogrammershangout.com/rules#what-is-modmail`
This PR updates the links in the ToC to see if this will make it link to the correct section properly.
This PR also fixes title formatting to add a newline between the title and the content:
Before:
After:
=> fix(rules): fix rule links and formatting

src/content/resources/javascript/promises/async-await.md
Fix a typo in the `async / await` JS article.
=> fix(content): fix typo in async / await article

src/content/resources/javascript/es6/arrow-functions.md
This is both adding more content to the existing article, as well as explaining the use of parameters inside immediate return arrow functions.
> The correction was changing it from telling the reader it was for one-line expression returns only, to logic-less expression returns as they could take up multiple lines in the case of it being an object or array or such.
=> Update ES6 Arrow Functions article

gatsby-config.js, gatsby-node.js, package-lock.json, package.json, src/pages/resources/404.tsx, src/pages/resources/index.tsx
closes #120 
Hello,
I tackled issue #120 and implemented a 404 page only active under the `/resources/` routes and suggests possible resources the user may have meant based off the entered link. 
What I did thus far:
- This uses Levenshtein distance (semantic difference of single character edits). 
- I've allowed for a semantic difference of 7 edits.
- Had to move `resources.tsx` to `resources/index.tsx`
- Added a package `gatsby-plugin-remove-trailing-slashes`, which treats `/page` and `/page/` as the same page, as there were some weird routing issues 
- This is probably worth noting in case you have to merge, since `package.json` is very volatile. The version probably won't matter too much. 
- The current versions of gastby and react in the repository (since my fork) also fixed some …
=> Resources 404 Page Implemented

src/pages/resources/404.tsx
During the TS type hint addition and slight refactoring, a stray quote was left in on PR https://github.com/the-programmers-hangout/website/pull/191. This quote would be in the redirection link, making the link invalid.
=> Fixed redirect links on resources 404

src/components/ResourcesList/index.tsx, src/components/ResourcesSidebar/index.tsx, src/utils/index.ts
This redirects the languages `resources/language/intro.md` to `/resources/language/`.
=> feat(resources): link to resources home from intro

src/components/ResourcesSidebar/index.tsx
This reorganizes the sidebar in priority, from intro, folders, and files (pages).
=> feat(resources): sort menu items: intro, folders, pages

src/components/ArchivesSidebar/index.tsx, src/components/ResourcesList/index.tsx, src/components/ResourcesSidebar/index.tsx, src/utils/index.ts
Given the mutative nature of `Array.sort()`, let's use Ramda's `sort`.
=> refact: use ramda for sorting

src/layouts/Layout/index.tsx
I noticed the index page ([https://theprogrammershangout.com/](https://theprogrammershangout.com/)) doesn't have a title or description which is detrimental to the SEO of the site.
I have gone ahead and added them.
As you are not using the `index.tsx` file in `src/pages` I have just added on to how you have currently done it.
=> Added a title and description for the index page

src/components/Waves/styles.tsx, src/images/waves-bot.svg, src/images/waves-top.svg
As the title suggests. From #110 
Preview
[https://gyazo.com/1fe13849187a57d15b9d4ac4b50a25fe](https://gyazo.com/1fe13849187a57d15b9d4ac4b50a25fe)
It looks the same on mobile, and IE looks fine (albeit not identical to chrome / firefox)
=> Fix svg waves across resolutions

gatsby-node.js, src/components/404LinkCorrection/index.tsx, src/components/404LinkCorrection/styles.tsx, src/pages/archives/404.tsx, src/pages/archives/index.tsx, src/pages/resources/404.tsx
Abstracted the logic in the resources' 404 page to work on any given collection. Implemented it for the tech spotlights. It should be easy enough to add the special 404 to a new collection if one appears as well. 
A couple of notes:
- Not sure if the threshold (number of single characters edits needed to consider a url a viable candidate) is too high for tech spotlights (since tech spotlights have the extra `what-is-`)
- We may need to refactor `gatsby-node.js`'s `onCreatePage` later to use a switch
- I tried to use proper types, but those may require some review :sweat_smile:
=> 404 Pages on Collections

src/content/archives/what-is-graphql.md, src/content/archives/what-is-redis.md, src/content/resources/cpp/multidimensional-arrays.md, src/content/resources/java/inheritance.md
closes #224
Eventually we would prefer defaulting to `sh` to trigger a proper codeblock, but could not figure out quickly how to do it with Prism.
=> fix: update codeblocks to use sh syntax

src/components/Breadcrumb/index.tsx, src/components/ResourcesSidebar/index.tsx
closes #198
Folders in resources that aren't the root folder have content.
[https://gyazo.com/2b0a2cee0c6b4ba586ad6384d85c010b](https://gyazo.com/2b0a2cee0c6b4ba586ad6384d85c010b)
To fix this I don't link the second or more folder when rendering the breadcrumbs (not the best solution but since we can't tell if an item's path exists it's the best I could come up with)
This is what it looks like after the fix
I also noticed that there was this error relating to unique key props in the resource sidebar
and have fixed it accordingly.
Thanks
=> Fixing breadcrumbs 404 & Unique key prop warning on resource sidebar

src/content/site/about.md
As discussed in Discord earlier, removing the "who owns this server" paragraph, as Fox's account is deleted now (and someone apparently took the name) and removing the paragraph seems like a good option to sort this issue.
=> (content): remove who owns this server paragraph

src/content/resources/javascript/variables.md
This PR fixes what I believe is an unintentional mistake in one of the Javascript code snippets in the variables article - a misplaced apostrophe. The typo wouldn't make sense as an intentional, demonstrative mistake in the context of the article.
=> Fixed unintentional code mistake in Javascript variables article

gatsby-config.js, package.json
As of https://github.com/gatsbyjs/gatsby/pull/23547 it's now included into Gatsby out of the box, so no longer necessary.
=> chore: remove now useless gatsby-plugin-typescript

src/components/Toc/index.tsx, src/content/site/rules.md
Fixes the inconsistent prefixes in rules, and correctly spaces out the prefix with the rest of the link (to avoid underline below a space!)
=> ui: tweak table of contents prefix

src/content/resources/topic/projects/http-project-guide/chapter-12.md, src/content/resources/topic/projects/http-project-guide/chapter-13.md
The chapter numbers in the titles of chapters 5, 12, and 13 were wrong. Just fixed the titles to show the correct chapter number.
=> Fixed typos in chapter titles

src/components/ResourcesHomeContent/styles.tsx
- Fixes #321 
- As far as I can tell, this does not break any other link styles.
Before:
After:
=> Reposition underline for resource links

src/components/PageContent/styles.tsx
You can observe this behavior by finding a page with long Table of Contents items and scrolling to the right.
Before:
After:
=> Prevent long TOC item overflow

src/components/Sidebar/styles.tsx
**Changes:**
- Prevents sidebar title color from changing when switched to light mode
- Fixes #330 
Before:
After:
=> Prevent sidebar title from changing colors

src/components/Home/styles.tsx, src/components/HomePartner/styles.tsx
**Changes:**
- Switches Home and HomePartner text and underline colors when light mode is enabled.
- Fixes #333 
Before:
After:
=> Allow Home text color to toggle for light mode

src/components/HeaderBarebone/styles.tsx
**Changes:**
- Sets `left` and `right` positions of component `Box` to `0px` for mobile layouts
- Fixes #341 
**Before:**
**After:**
=> Center resource header box on firefox mobile layout

src/components/ArchivesSidebar/styles.tsx
**Changes:**
- Converts link underline from `border-bottom` to `text-decoration`
- Fixes #344 
**Screenshots:**
Before:
After:
=> Prevent spotlight link underlines from extending past text

src/components/PageContent/styles.tsx
**Changes:**
- Specify Content component width with `vw` units instead of a percentage
- Remove unnecessary `width` property
- Fix #349 
**Screenshots:**
Before:
After:
=> Prevent ToC from repositioning when zoom is <100%

src/components/ResourcesSidebar/index.tsx
This PR fixes #274 
Before: 
After:
=> Open resource intro on selecting

gatsby-node.js
This PR fixes #214 
`path.join` in Windows converts `/` in paths to `\`, so the path of those pages are converted to `/resources\javascript\iterative-vs-functional.md` but browsers can't use `\` in URL so it's redirected as 404 page.
`path.posix.join` ensures it's always use `/` regardless of OS.
Edit: Shoutout to my brother for lending me his PC.
=> Change `path.join` to `path.posix.join` ensuring path uses `/` not `\`

src/components/PageContent/styles.tsx
This PR fixes #352 
Before:
After:
=> Add width property - fix toc positioning

src/content/site/bots.md
- Update keeper prefix. The old prefix should have been "keeper", not "keeperhelp", but this was changed to "keeper!" to fix this confusion.
- Update "+beginners" mention to "++beginners" for consistency with the rest of the commands.
=> content: update bots page content

src/components/Markdown/env.ts, src/components/Markdown/index.tsx
Adds highlighting support for dotenv codeblocks. Fixes #367 
highlighting strings after `=` without capturing it requires positive lookahead, which isn't supported in all browsers, so I added a check just in case, but I wasn't able to define the `string` settings after defining `attribute` and `operator` separately, for some, reason adding `string`'s config afterwards wasn't working, so I had to repeat a little code in the if blocks.
=> Adds dotenv highlight support for Prism

src/content/resources/language/javascript/cannot-read-property.md
The question of "Cannot read property `abc` of `null`/`undefined`" arises often in #javascript and #discord-js channels. I write this page so that hopefully the same responses and suggestions will not be written one time for each asker.
=> Add "Cannot read property "abc" of null/undefined."

src/content/resources/language/python/intro.md
The target repository change the directory structure resulting in a dead link.
=> Replace the link to Python free book with a new one

src/components/Markdown/env.ts
Fixes a RegExp validation error caused when building and executing
a regular expression with lookbehind syntax on Safari.
This issue causes a white screen when running `npm start` on Safari
browser.
=> Fix | Safari support for PrismJS env configuration

src/content/site/bots.md
The server uses mongo version of emourge but the current source points the postgres version.
=> Change source link of emourge in bots list

README.md, src/components/Container/styles.tsx
This fixes the anchor link offset, which did not previously take the fixed header into consideration.
=> Offset anchor links while taking the fixed header into consideration

src/components/HeaderBarebone/styles.tsx, src/components/Markdown/styles.tsx, src/components/Sidebar/styles.tsx
There are still some issues regarding the header, i dont really like how it is on mobile, it takes up a lot of vertical space and doesn't provide much info, i think it should be removed and instead adding the page path info in the topmost part of the page.
I changed the sidemenu top bar (where there is the logo and tph logo) to have the same size as the header.
Fixes issue #412 
Changed the way the side menu appears, from using left/right to use transform
=> fixed #412, fixed #TODO in side menu animation, fixed <a> text being on top of the header

src/content/spotlights/what-is-tailwind.md
I think the user profiles script needs to be updated but that can and should be done in a different pr.
=> Tech Spotlight: What is Tailwind?

src/content/resources/language/c-sharp/access-modifiers.md, src/content/resources/language/c-sharp/intro.md
Make sure the C# resources are up-to-date.
=> Update c# resources
